/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.nML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.nml.nML.ConditionCS;
import org.xtext.example.nml.nML.NMLPackage;
import org.xtext.example.nml.nML.StatementCS;
import org.xtext.example.nml.nML.TransferCP;
import org.xtext.example.nml.nML.modelListCS;
import org.xtext.example.nml.nML.modelTypeCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transfer CP</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.nml.nML.impl.TransferCPImpl#getOwnedModels <em>Owned Models</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.impl.TransferCPImpl#getOwnedLists <em>Owned Lists</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.impl.TransferCPImpl#getOwnedConditions <em>Owned Conditions</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.impl.TransferCPImpl#getOwnedStatement <em>Owned Statement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransferCPImpl extends MinimalEObjectImpl.Container implements TransferCP
{
  /**
   * The cached value of the '{@link #getOwnedModels() <em>Owned Models</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedModels()
   * @generated
   * @ordered
   */
  protected EList<modelTypeCS> ownedModels;

  /**
   * The cached value of the '{@link #getOwnedLists() <em>Owned Lists</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedLists()
   * @generated
   * @ordered
   */
  protected EList<modelListCS> ownedLists;

  /**
   * The cached value of the '{@link #getOwnedConditions() <em>Owned Conditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedConditions()
   * @generated
   * @ordered
   */
  protected EList<ConditionCS> ownedConditions;

  /**
   * The cached value of the '{@link #getOwnedStatement() <em>Owned Statement</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedStatement()
   * @generated
   * @ordered
   */
  protected EList<StatementCS> ownedStatement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransferCPImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NMLPackage.Literals.TRANSFER_CP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<modelTypeCS> getOwnedModels()
  {
    if (ownedModels == null)
    {
      ownedModels = new EObjectContainmentEList<modelTypeCS>(modelTypeCS.class, this, NMLPackage.TRANSFER_CP__OWNED_MODELS);
    }
    return ownedModels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<modelListCS> getOwnedLists()
  {
    if (ownedLists == null)
    {
      ownedLists = new EObjectContainmentEList<modelListCS>(modelListCS.class, this, NMLPackage.TRANSFER_CP__OWNED_LISTS);
    }
    return ownedLists;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ConditionCS> getOwnedConditions()
  {
    if (ownedConditions == null)
    {
      ownedConditions = new EObjectContainmentEList<ConditionCS>(ConditionCS.class, this, NMLPackage.TRANSFER_CP__OWNED_CONDITIONS);
    }
    return ownedConditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<StatementCS> getOwnedStatement()
  {
    if (ownedStatement == null)
    {
      ownedStatement = new EObjectContainmentEList<StatementCS>(StatementCS.class, this, NMLPackage.TRANSFER_CP__OWNED_STATEMENT);
    }
    return ownedStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NMLPackage.TRANSFER_CP__OWNED_MODELS:
        return ((InternalEList<?>)getOwnedModels()).basicRemove(otherEnd, msgs);
      case NMLPackage.TRANSFER_CP__OWNED_LISTS:
        return ((InternalEList<?>)getOwnedLists()).basicRemove(otherEnd, msgs);
      case NMLPackage.TRANSFER_CP__OWNED_CONDITIONS:
        return ((InternalEList<?>)getOwnedConditions()).basicRemove(otherEnd, msgs);
      case NMLPackage.TRANSFER_CP__OWNED_STATEMENT:
        return ((InternalEList<?>)getOwnedStatement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NMLPackage.TRANSFER_CP__OWNED_MODELS:
        return getOwnedModels();
      case NMLPackage.TRANSFER_CP__OWNED_LISTS:
        return getOwnedLists();
      case NMLPackage.TRANSFER_CP__OWNED_CONDITIONS:
        return getOwnedConditions();
      case NMLPackage.TRANSFER_CP__OWNED_STATEMENT:
        return getOwnedStatement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NMLPackage.TRANSFER_CP__OWNED_MODELS:
        getOwnedModels().clear();
        getOwnedModels().addAll((Collection<? extends modelTypeCS>)newValue);
        return;
      case NMLPackage.TRANSFER_CP__OWNED_LISTS:
        getOwnedLists().clear();
        getOwnedLists().addAll((Collection<? extends modelListCS>)newValue);
        return;
      case NMLPackage.TRANSFER_CP__OWNED_CONDITIONS:
        getOwnedConditions().clear();
        getOwnedConditions().addAll((Collection<? extends ConditionCS>)newValue);
        return;
      case NMLPackage.TRANSFER_CP__OWNED_STATEMENT:
        getOwnedStatement().clear();
        getOwnedStatement().addAll((Collection<? extends StatementCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NMLPackage.TRANSFER_CP__OWNED_MODELS:
        getOwnedModels().clear();
        return;
      case NMLPackage.TRANSFER_CP__OWNED_LISTS:
        getOwnedLists().clear();
        return;
      case NMLPackage.TRANSFER_CP__OWNED_CONDITIONS:
        getOwnedConditions().clear();
        return;
      case NMLPackage.TRANSFER_CP__OWNED_STATEMENT:
        getOwnedStatement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NMLPackage.TRANSFER_CP__OWNED_MODELS:
        return ownedModels != null && !ownedModels.isEmpty();
      case NMLPackage.TRANSFER_CP__OWNED_LISTS:
        return ownedLists != null && !ownedLists.isEmpty();
      case NMLPackage.TRANSFER_CP__OWNED_CONDITIONS:
        return ownedConditions != null && !ownedConditions.isEmpty();
      case NMLPackage.TRANSFER_CP__OWNED_STATEMENT:
        return ownedStatement != null && !ownedStatement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TransferCPImpl
