/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.scoping;

import org.eclipse.ocl.xtext.essentialocl.scoping.EssentialOCLScopeProvider;

public abstract class AbstractNMLScopeProvider extends EssentialOCLScopeProvider {
}
