/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.nml.ui.internal.NmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(NmlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		NmlActivator activator = NmlActivator.getInstance();
		return activator != null ? activator.getInjector(NmlActivator.ORG_XTEXT_EXAMPLE_NML_NML) : null;
	}

}
