/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.nML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.nml.nML.NMLPackage
 * @generated
 */
public interface NMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NMLFactory eINSTANCE = org.xtext.example.nml.nML.impl.NMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Top Level CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Level CP</em>'.
   * @generated
   */
  TopLevelCP createTopLevelCP();

  /**
   * Returns a new object of class '<em>Domain CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domain CP</em>'.
   * @generated
   */
  DomainCP createDomainCP();

  /**
   * Returns a new object of class '<em>Octopus CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Octopus CP</em>'.
   * @generated
   */
  OctopusCP createOctopusCP();

  /**
   * Returns a new object of class '<em>Ours CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ours CP</em>'.
   * @generated
   */
  OursCP createOursCP();

  /**
   * Returns a new object of class '<em>Transformation CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformation CP</em>'.
   * @generated
   */
  TransformationCP createTransformationCP();

  /**
   * Returns a new object of class '<em>model Type CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>model Type CS</em>'.
   * @generated
   */
  modelTypeCS createmodelTypeCS();

  /**
   * Returns a new object of class '<em>model Order CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>model Order CS</em>'.
   * @generated
   */
  modelOrderCS createmodelOrderCS();

  /**
   * Returns a new object of class '<em>Statement CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement CS</em>'.
   * @generated
   */
  StatementCS createStatementCS();

  /**
   * Returns a new object of class '<em>Condition CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition CS</em>'.
   * @generated
   */
  ConditionCS createConditionCS();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  NMLPackage getNMLPackage();

} //NMLFactory
