/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.nML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.nml.nML.NMLFactory
 * @model kind="package"
 * @generated
 */
public interface NMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "nML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/nml/NML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "nML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NMLPackage eINSTANCE = org.xtext.example.nml.nML.impl.NMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.TopLevelCPImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getTopLevelCP()
   * @generated
   */
  int TOP_LEVEL_CP = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__NAME = 0;

  /**
   * The feature id for the '<em><b>Owned Domains</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_DOMAINS = 1;

  /**
   * The feature id for the '<em><b>Owned Pre</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_PRE = 2;

  /**
   * The feature id for the '<em><b>Owned Octopus</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_OCTOPUS = 3;

  /**
   * The feature id for the '<em><b>Owned Ours</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_OURS = 4;

  /**
   * The feature id for the '<em><b>Owned Transformation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_TRANSFORMATION = 5;

  /**
   * The number of structural features of the '<em>Top Level CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.DomainCPImpl <em>Domain CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.DomainCPImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getDomainCP()
   * @generated
   */
  int DOMAIN_CP = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_CP__NAME = 0;

  /**
   * The feature id for the '<em><b>Ns URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_CP__NS_URI = 1;

  /**
   * The number of structural features of the '<em>Domain CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_CP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.OctopusCPImpl <em>Octopus CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.OctopusCPImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getOctopusCP()
   * @generated
   */
  int OCTOPUS_CP = 2;

  /**
   * The feature id for the '<em><b>Owned Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCTOPUS_CP__OWNED_MODELS = 0;

  /**
   * The feature id for the '<em><b>Owned Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCTOPUS_CP__OWNED_CONDITIONS = 1;

  /**
   * The number of structural features of the '<em>Octopus CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCTOPUS_CP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.OursCPImpl <em>Ours CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.OursCPImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getOursCP()
   * @generated
   */
  int OURS_CP = 3;

  /**
   * The feature id for the '<em><b>Owned Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OURS_CP__OWNED_MODELS = 0;

  /**
   * The feature id for the '<em><b>Owned Orders</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OURS_CP__OWNED_ORDERS = 1;

  /**
   * The feature id for the '<em><b>Owned Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OURS_CP__OWNED_STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Ours CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OURS_CP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.TransferCPImpl <em>Transfer CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.TransferCPImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getTransferCP()
   * @generated
   */
  int TRANSFER_CP = 4;

  /**
   * The feature id for the '<em><b>Owned Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFER_CP__OWNED_MODELS = 0;

  /**
   * The feature id for the '<em><b>Owned Lists</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFER_CP__OWNED_LISTS = 1;

  /**
   * The feature id for the '<em><b>Owned Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFER_CP__OWNED_CONDITIONS = 2;

  /**
   * The feature id for the '<em><b>Owned Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFER_CP__OWNED_STATEMENT = 3;

  /**
   * The number of structural features of the '<em>Transfer CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFER_CP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.modelTypeCSImpl <em>model Type CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.modelTypeCSImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelTypeCS()
   * @generated
   */
  int MODEL_TYPE_CS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_TYPE_CS__NAME = 0;

  /**
   * The number of structural features of the '<em>model Type CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_TYPE_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.modelOrderCSImpl <em>model Order CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.modelOrderCSImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelOrderCS()
   * @generated
   */
  int MODEL_ORDER_CS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ORDER_CS__NAME = 0;

  /**
   * The number of structural features of the '<em>model Order CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ORDER_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.modelListCSImpl <em>model List CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.modelListCSImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelListCS()
   * @generated
   */
  int MODEL_LIST_CS = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST_CS__NAME = 0;

  /**
   * The number of structural features of the '<em>model List CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.StatementCSImpl <em>Statement CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.StatementCSImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getStatementCS()
   * @generated
   */
  int STATEMENT_CS = 8;

  /**
   * The feature id for the '<em><b>Owned Element</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_CS__OWNED_ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Statement CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.nml.nML.impl.ConditionCSImpl <em>Condition CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.nml.nML.impl.ConditionCSImpl
   * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getConditionCS()
   * @generated
   */
  int CONDITION_CS = 9;

  /**
   * The feature id for the '<em><b>Owned Element</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_CS__OWNED_ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Condition CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_CS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.TopLevelCP <em>Top Level CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Level CP</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP
   * @generated
   */
  EClass getTopLevelCP();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.TopLevelCP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getName()
   * @see #getTopLevelCP()
   * @generated
   */
  EAttribute getTopLevelCP_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedDomains <em>Owned Domains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Domains</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getOwnedDomains()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedDomains();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedPre <em>Owned Pre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Pre</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getOwnedPre()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedPre();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedOctopus <em>Owned Octopus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Octopus</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getOwnedOctopus()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedOctopus();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedOurs <em>Owned Ours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Ours</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getOwnedOurs()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedOurs();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedTransformation <em>Owned Transformation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Transformation</em>'.
   * @see org.xtext.example.nml.nML.TopLevelCP#getOwnedTransformation()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedTransformation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.DomainCP <em>Domain CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain CP</em>'.
   * @see org.xtext.example.nml.nML.DomainCP
   * @generated
   */
  EClass getDomainCP();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.DomainCP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.nml.nML.DomainCP#getName()
   * @see #getDomainCP()
   * @generated
   */
  EAttribute getDomainCP_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.DomainCP#getNsURI <em>Ns URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ns URI</em>'.
   * @see org.xtext.example.nml.nML.DomainCP#getNsURI()
   * @see #getDomainCP()
   * @generated
   */
  EAttribute getDomainCP_NsURI();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.OctopusCP <em>Octopus CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Octopus CP</em>'.
   * @see org.xtext.example.nml.nML.OctopusCP
   * @generated
   */
  EClass getOctopusCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.OctopusCP#getOwnedModels <em>Owned Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Models</em>'.
   * @see org.xtext.example.nml.nML.OctopusCP#getOwnedModels()
   * @see #getOctopusCP()
   * @generated
   */
  EReference getOctopusCP_OwnedModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.OctopusCP#getOwnedConditions <em>Owned Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Conditions</em>'.
   * @see org.xtext.example.nml.nML.OctopusCP#getOwnedConditions()
   * @see #getOctopusCP()
   * @generated
   */
  EReference getOctopusCP_OwnedConditions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.OursCP <em>Ours CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ours CP</em>'.
   * @see org.xtext.example.nml.nML.OursCP
   * @generated
   */
  EClass getOursCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.OursCP#getOwnedModels <em>Owned Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Models</em>'.
   * @see org.xtext.example.nml.nML.OursCP#getOwnedModels()
   * @see #getOursCP()
   * @generated
   */
  EReference getOursCP_OwnedModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.OursCP#getOwnedOrders <em>Owned Orders</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Orders</em>'.
   * @see org.xtext.example.nml.nML.OursCP#getOwnedOrders()
   * @see #getOursCP()
   * @generated
   */
  EReference getOursCP_OwnedOrders();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.OursCP#getOwnedStatement <em>Owned Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Statement</em>'.
   * @see org.xtext.example.nml.nML.OursCP#getOwnedStatement()
   * @see #getOursCP()
   * @generated
   */
  EReference getOursCP_OwnedStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.TransferCP <em>Transfer CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transfer CP</em>'.
   * @see org.xtext.example.nml.nML.TransferCP
   * @generated
   */
  EClass getTransferCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TransferCP#getOwnedModels <em>Owned Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Models</em>'.
   * @see org.xtext.example.nml.nML.TransferCP#getOwnedModels()
   * @see #getTransferCP()
   * @generated
   */
  EReference getTransferCP_OwnedModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TransferCP#getOwnedLists <em>Owned Lists</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Lists</em>'.
   * @see org.xtext.example.nml.nML.TransferCP#getOwnedLists()
   * @see #getTransferCP()
   * @generated
   */
  EReference getTransferCP_OwnedLists();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TransferCP#getOwnedConditions <em>Owned Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Conditions</em>'.
   * @see org.xtext.example.nml.nML.TransferCP#getOwnedConditions()
   * @see #getTransferCP()
   * @generated
   */
  EReference getTransferCP_OwnedConditions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.nml.nML.TransferCP#getOwnedStatement <em>Owned Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Statement</em>'.
   * @see org.xtext.example.nml.nML.TransferCP#getOwnedStatement()
   * @see #getTransferCP()
   * @generated
   */
  EReference getTransferCP_OwnedStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.modelTypeCS <em>model Type CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>model Type CS</em>'.
   * @see org.xtext.example.nml.nML.modelTypeCS
   * @generated
   */
  EClass getmodelTypeCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.modelTypeCS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.nml.nML.modelTypeCS#getName()
   * @see #getmodelTypeCS()
   * @generated
   */
  EAttribute getmodelTypeCS_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.modelOrderCS <em>model Order CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>model Order CS</em>'.
   * @see org.xtext.example.nml.nML.modelOrderCS
   * @generated
   */
  EClass getmodelOrderCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.modelOrderCS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.nml.nML.modelOrderCS#getName()
   * @see #getmodelOrderCS()
   * @generated
   */
  EAttribute getmodelOrderCS_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.modelListCS <em>model List CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>model List CS</em>'.
   * @see org.xtext.example.nml.nML.modelListCS
   * @generated
   */
  EClass getmodelListCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.nml.nML.modelListCS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.nml.nML.modelListCS#getName()
   * @see #getmodelListCS()
   * @generated
   */
  EAttribute getmodelListCS_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.StatementCS <em>Statement CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement CS</em>'.
   * @see org.xtext.example.nml.nML.StatementCS
   * @generated
   */
  EClass getStatementCS();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.nml.nML.StatementCS#getOwnedElement <em>Owned Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Owned Element</em>'.
   * @see org.xtext.example.nml.nML.StatementCS#getOwnedElement()
   * @see #getStatementCS()
   * @generated
   */
  EAttribute getStatementCS_OwnedElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.nml.nML.ConditionCS <em>Condition CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition CS</em>'.
   * @see org.xtext.example.nml.nML.ConditionCS
   * @generated
   */
  EClass getConditionCS();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.nml.nML.ConditionCS#getOwnedElement <em>Owned Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Owned Element</em>'.
   * @see org.xtext.example.nml.nML.ConditionCS#getOwnedElement()
   * @see #getConditionCS()
   * @generated
   */
  EAttribute getConditionCS_OwnedElement();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  NMLFactory getNMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.TopLevelCPImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getTopLevelCP()
     * @generated
     */
    EClass TOP_LEVEL_CP = eINSTANCE.getTopLevelCP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_LEVEL_CP__NAME = eINSTANCE.getTopLevelCP_Name();

    /**
     * The meta object literal for the '<em><b>Owned Domains</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_DOMAINS = eINSTANCE.getTopLevelCP_OwnedDomains();

    /**
     * The meta object literal for the '<em><b>Owned Pre</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_PRE = eINSTANCE.getTopLevelCP_OwnedPre();

    /**
     * The meta object literal for the '<em><b>Owned Octopus</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_OCTOPUS = eINSTANCE.getTopLevelCP_OwnedOctopus();

    /**
     * The meta object literal for the '<em><b>Owned Ours</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_OURS = eINSTANCE.getTopLevelCP_OwnedOurs();

    /**
     * The meta object literal for the '<em><b>Owned Transformation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_TRANSFORMATION = eINSTANCE.getTopLevelCP_OwnedTransformation();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.DomainCPImpl <em>Domain CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.DomainCPImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getDomainCP()
     * @generated
     */
    EClass DOMAIN_CP = eINSTANCE.getDomainCP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_CP__NAME = eINSTANCE.getDomainCP_Name();

    /**
     * The meta object literal for the '<em><b>Ns URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_CP__NS_URI = eINSTANCE.getDomainCP_NsURI();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.OctopusCPImpl <em>Octopus CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.OctopusCPImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getOctopusCP()
     * @generated
     */
    EClass OCTOPUS_CP = eINSTANCE.getOctopusCP();

    /**
     * The meta object literal for the '<em><b>Owned Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCTOPUS_CP__OWNED_MODELS = eINSTANCE.getOctopusCP_OwnedModels();

    /**
     * The meta object literal for the '<em><b>Owned Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCTOPUS_CP__OWNED_CONDITIONS = eINSTANCE.getOctopusCP_OwnedConditions();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.OursCPImpl <em>Ours CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.OursCPImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getOursCP()
     * @generated
     */
    EClass OURS_CP = eINSTANCE.getOursCP();

    /**
     * The meta object literal for the '<em><b>Owned Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OURS_CP__OWNED_MODELS = eINSTANCE.getOursCP_OwnedModels();

    /**
     * The meta object literal for the '<em><b>Owned Orders</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OURS_CP__OWNED_ORDERS = eINSTANCE.getOursCP_OwnedOrders();

    /**
     * The meta object literal for the '<em><b>Owned Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OURS_CP__OWNED_STATEMENT = eINSTANCE.getOursCP_OwnedStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.TransferCPImpl <em>Transfer CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.TransferCPImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getTransferCP()
     * @generated
     */
    EClass TRANSFER_CP = eINSTANCE.getTransferCP();

    /**
     * The meta object literal for the '<em><b>Owned Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFER_CP__OWNED_MODELS = eINSTANCE.getTransferCP_OwnedModels();

    /**
     * The meta object literal for the '<em><b>Owned Lists</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFER_CP__OWNED_LISTS = eINSTANCE.getTransferCP_OwnedLists();

    /**
     * The meta object literal for the '<em><b>Owned Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFER_CP__OWNED_CONDITIONS = eINSTANCE.getTransferCP_OwnedConditions();

    /**
     * The meta object literal for the '<em><b>Owned Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFER_CP__OWNED_STATEMENT = eINSTANCE.getTransferCP_OwnedStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.modelTypeCSImpl <em>model Type CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.modelTypeCSImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelTypeCS()
     * @generated
     */
    EClass MODEL_TYPE_CS = eINSTANCE.getmodelTypeCS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_TYPE_CS__NAME = eINSTANCE.getmodelTypeCS_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.modelOrderCSImpl <em>model Order CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.modelOrderCSImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelOrderCS()
     * @generated
     */
    EClass MODEL_ORDER_CS = eINSTANCE.getmodelOrderCS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_ORDER_CS__NAME = eINSTANCE.getmodelOrderCS_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.modelListCSImpl <em>model List CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.modelListCSImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getmodelListCS()
     * @generated
     */
    EClass MODEL_LIST_CS = eINSTANCE.getmodelListCS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_LIST_CS__NAME = eINSTANCE.getmodelListCS_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.StatementCSImpl <em>Statement CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.StatementCSImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getStatementCS()
     * @generated
     */
    EClass STATEMENT_CS = eINSTANCE.getStatementCS();

    /**
     * The meta object literal for the '<em><b>Owned Element</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT_CS__OWNED_ELEMENT = eINSTANCE.getStatementCS_OwnedElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.nml.nML.impl.ConditionCSImpl <em>Condition CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.nml.nML.impl.ConditionCSImpl
     * @see org.xtext.example.nml.nML.impl.NMLPackageImpl#getConditionCS()
     * @generated
     */
    EClass CONDITION_CS = eINSTANCE.getConditionCS();

    /**
     * The meta object literal for the '<em><b>Owned Element</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_CS__OWNED_ELEMENT = eINSTANCE.getConditionCS_OwnedElement();

  }

} //NMLPackage
