/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.nML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.nml.nML.StatementCS#getOwnedElement <em>Owned Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.nml.nML.NMLPackage#getStatementCS()
 * @model
 * @generated
 */
public interface StatementCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Element</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Element</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Element</em>' attribute list.
   * @see org.xtext.example.nml.nML.NMLPackage#getStatementCS_OwnedElement()
   * @model unique="false"
   * @generated
   */
  EList<String> getOwnedElement();

} // StatementCS
