/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.nML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top Level CP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedDomains <em>Owned Domains</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedPre <em>Owned Pre</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedOctopus <em>Owned Octopus</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedOurs <em>Owned Ours</em>}</li>
 *   <li>{@link org.xtext.example.nml.nML.TopLevelCP#getOwnedTransformation <em>Owned Transformation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP()
 * @model
 * @generated
 */
public interface TopLevelCP extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.nml.nML.TopLevelCP#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owned Domains</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.nml.nML.DomainCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Domains</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Domains</em>' containment reference list.
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_OwnedDomains()
   * @model containment="true"
   * @generated
   */
  EList<DomainCP> getOwnedDomains();

  /**
   * Returns the value of the '<em><b>Owned Pre</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.nml.nML.StatementCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Pre</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Pre</em>' containment reference list.
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_OwnedPre()
   * @model containment="true"
   * @generated
   */
  EList<StatementCS> getOwnedPre();

  /**
   * Returns the value of the '<em><b>Owned Octopus</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.nml.nML.OctopusCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Octopus</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Octopus</em>' containment reference list.
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_OwnedOctopus()
   * @model containment="true"
   * @generated
   */
  EList<OctopusCP> getOwnedOctopus();

  /**
   * Returns the value of the '<em><b>Owned Ours</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.nml.nML.OursCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Ours</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Ours</em>' containment reference list.
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_OwnedOurs()
   * @model containment="true"
   * @generated
   */
  EList<OursCP> getOwnedOurs();

  /**
   * Returns the value of the '<em><b>Owned Transformation</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.nml.nML.TransferCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Transformation</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Transformation</em>' containment reference list.
   * @see org.xtext.example.nml.nML.NMLPackage#getTopLevelCP_OwnedTransformation()
   * @model containment="true"
   * @generated
   */
  EList<TransferCP> getOwnedTransformation();

} // TopLevelCP
