/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.nml.ui.AbstractNMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class NMLUiModule extends AbstractNMLUiModule {
  public NMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
