/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.validation;

import org.xtext.example.nml.validation.AbstractNMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class NMLValidator extends AbstractNMLValidator {
}
