/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml;

import org.xtext.example.nml.AbstractNMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NMLRuntimeModule extends AbstractNMLRuntimeModule {
}
