/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NMLStandaloneSetup extends NMLStandaloneSetupGenerated {

	def static void doSetup() {
		new NMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
