/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.nml.NMLRuntimeModule;
import org.xtext.example.nml.NMLStandaloneSetup;
import org.xtext.example.nml.ide.NMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class NMLIdeSetup extends NMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    NMLRuntimeModule _nMLRuntimeModule = new NMLRuntimeModule();
    NMLIdeModule _nMLIdeModule = new NMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_nMLRuntimeModule, _nMLIdeModule));
  }
}
