/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.ide;

import org.xtext.example.nml.ide.AbstractNMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class NMLIdeModule extends AbstractNMLIdeModule {
}
