/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.nml.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.nml.NMLRuntimeModule
import org.xtext.example.nml.NMLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class NMLIdeSetup extends NMLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new NMLRuntimeModule, new NMLIdeModule))
	}
	
}
